name: TWRP CI
on:
  workflow_dispatch:
jobs:
  build:
    name: TWRP Build CI
    runs-on: ubuntu-22.04
    env:
      OEM: samsung
      DEVICE: i9300
      BRANCH: twrp-6.0
    steps:
      - uses: actions/checkout@v7
      - name: Installing build dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex axel g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb && sudo dpkg -i libtinfo5_6.3-2_amd64.deb && rm -f libtinfo5_6.3-2_amd64.deb
          wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.3-2_amd64.deb && sudo dpkg -i libncurses5_6.3-2_amd64.deb && rm -f libncurses5_6.3-2_amd64.deb
          cd /usr/local/src
          sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          sudo tar xvf Python-2.7.18.tgz
          cd Python-2.7.18
          sudo ./configure --enable-optimizations
          sudo make altinstall
          sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python2
          sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Syncing TWRP sources
        run: |
          mkdir ~/TWRP
          cd ~/TWRP
          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --depth=1 --branch android-7.1.2_r38 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8
          git clone --depth=1 --branch twrp-6.0 --single-branch https://github.com/notnoelchannel2/twrp_device_samsung_i9300.git device/samsung/i9300
          git clone --depth=1 --branch cm-14.1 --single-branch https://github.com/unlegacy-devices/android_kernel_samsung_smdk4412/ kernel/samsung/smdk4412
      - name: Building TWRP
        run: |
          cd ~/TWRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL="C"
          lunch omni_i9300-eng
          make -j$(nproc --all) recoveryimage
      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v6
        with:
          name: TWRP
          path: /home/runner/TWRP/out/target/product/i9300/recovery.*
